### PR TITLE
fix: scrollable query list when overflowed

### LINKED ISSUE #42: Non scrollable query list
Hey!

I just discovered this devtools projects for the `react-query` library. And it seems really nice! Thank you very much for all the hard work!

As I wanted to use it to debug an application I'm working on, I noticed that the general query list is not scrollable.

To illustrate this, here is a screenshot I took while using the [demo](https://codesandbox.io/s/github/tannerlinsley/react-query/tree/master/examples/playground):

Screenshot 2020-07-15 at 17 34 53

In order to make it observable, I had to reduce a lot the size of the browser window as the demo doesn't use many queries. But when working on a slightly bigger application with around 12 queries registered by the dev tools, we can't browse them.

As a simple workaround, I just manually forced the main container to have its overflow set to `auto`. But I reckon that the desired effect would be to only have the query list scrolling.

Have a great one!

### PR DESCRIPTION
**Pull request by kamranayub**
Fixes #42 

Let me know if you think there's a better way! This works in Chrome when I tested with >12 queries.

Example:

image

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -295,6 +295,7 @@ export const ReactQueryDevtoolsPanel = React.forwardRef(
             style={{
               flex: '1 1 500px',
               minHeight: '40%',
+              maxHeight: '100%',
```
Comment (kamranayub) [inline src/index.js:298]: Container will extend beyond the dev tools panel without this; this creates a constraint that will generate overflow.

File: src/index.js [hunk 2]
```diff
@@ -408,6 +409,7 @@ export const ReactQueryDevtoolsPanel = React.forwardRef(
             <div
               style={{
                 overflow: 'auto',
+                overflowY: 'scroll'
```
Comment (kamranayub) [inline src/index.js]: _probably_ could just be `overflow: 'auto scroll'`
